# Generated by Django 5.0.3 on 2024-03-10 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('interval_min', models.FloatField()),
                ('interval_max', models.FloatField()),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
                ('indicator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oncology.indicator')),
            ],
        ),
        migrations.CreateModel(
            name='PatientTests',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('analysis_date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('diagnosis', models.CharField()),
                ('region', models.CharField()),
                ('diagnosis_comment', models.TextField(blank=True, null=True)),
                ('operation_comment', models.TextField(blank=True, null=True)),
                ('chemoterapy_comment', models.TextField(blank=True, null=True)),
                ('patient_test_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oncology.patienttests')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('analysis_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oncology.analysis')),
            ],
        ),
        migrations.AddField(
            model_name='patienttests',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oncology.test'),
        ),
    ]
