# Generated by Django 5.0.3 on 2024-03-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='interval_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='interval_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
