# Generated by Django 5.0.3 on 2024-04-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0002_alter_indicator_interval_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graphic', models.ImageField(upload_to='media')),
            ],
        ),
    ]
