# Generated by Django 5.0.3 on 2024-04-02 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0003_graphic'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='patient_test_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='oncology.patienttests'),
            preserve_default=False,
        ),
    ]
