# Generated by Django 5.0.3 on 2024-03-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0003_copyrightinfo_subjectinfo_alter_analysis_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='login',
        ),
    ]
