# Generated by Django 5.0.3 on 2024-04-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0004_graphic_patient_test_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='interval_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='interval_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
