# Generated by Django 5.0.3 on 2024-03-24 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0004_remove_doctor_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_test_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='oncology.patienttests'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='region',
            field=models.CharField(max_length=255),
        ),
    ]
