# Generated by Django 5.0.3 on 2024-04-16 07:41

import oncology.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncology', '0005_alter_analysis_value_alter_indicator_interval_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(validators=[oncology.models.validate_date]),
        ),
    ]
